"""Cisco show-command catalog used by the Network API. Read-only."""

OPERATIONS = {
    "device_facts": "show version",
    "device_health": "show version",
    "interfaces": "show ip interface brief",
    "interfaces_status": "show ip interface brief",
    "interfaces_counters": "show interfaces",
    "arp": "show ip arp",
    "mac": "show mac address-table",
    "vlans": "show vlan brief",
    "trunks": "show interfaces trunk",
    "stp": "show spanning-tree",
    "routing": "show ip route",
    "vrf": "show vrf",
    "ospf": "show ip ospf",
    "ospf_neighbors": "show ip ospf neighbor",
    "ospf_interfaces": "show ip ospf interface brief",
    "bgp": "show ip bgp summary",
    "bgp_neighbors": "show ip bgp summary",
    "bgp_routes": "show ip bgp",
    "cdp": "show cdp neighbors",
    "lldp": "show lldp neighbors",
    "vpn": "show crypto session",
    "ipsec": "show crypto ipsec sa",
    "dhcp": "show ip dhcp binding",
    "wan": "show ip interface brief",
    "wan_errors": "show interfaces",
    "sdwan_bfd": "show sdwan bfd sessions",
    "sdwan_omp": "show sdwan omp peers",
    "sdwan_control": "show sdwan control connections",
    "logging": "show logging | include %",
    "environment": "show environment",
    "config_running": "show running-config",
    "config_startup": "show startup-config",
}

PLATFORM_MAP = {
    "cisco_ios": "cisco_ios",
    "cisco_iosxe": "cisco_ios",
    "cisco_ios-xe": "cisco_xe",
    "cisco_xe": "cisco_xe",
    "cisco_nxos": "cisco_nxos",
    "cisco_asa": "cisco_asa",
    "viptela": "cisco_viptela",
    "cisco_sdwan": "cisco_viptela",
    "arista_eos": "arista_eos",
    "juniper_junos": "juniper_junos",
}
